### ISSUE TITLE
Nieuwe versie ISO 19115

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/raamwerk-geostandaarden#10]
Het Raamwerk verwijst naar oude versies van ISO 19115. Deze zijn nog in gebruik in INSPIRE. Maar moeten we de nieuwe ISO 19115 niet toch ook noemen en uitleggen waarom we die niet hanteren?

**Comment by MichelGrothe** [comment]
Ik heb Ine gevraagd om enkele regels daarvoor aan te leveren, zodat we dit in een Noot kunnen verduidelijken.

**Comment by MichelGrothe** [comment]
Noot is toegevoegd.
