### ISSUE TITLE
Verwijzing naar een CRS

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/raamwerk-geostandaarden#11]
In paragraaf [Overzicht standaarden voor coördinaatreferentiesystemen](https://geonovum.github.io/raamwerk-geostandaarden/#overzicht-standaarden-voor-coordinaatreferentiesystemen) wordt gezegd: 

> Voor [specificatie en naamgeving van een CRS](https://geonovum.github.io/HR-CRS-Gebruik/#naamgeving-van-crs) kunnen Name Type Sepcifications (NTS) of Uniform Resource names (URN) gebruikt worden

Het is echter ook mogelijk om een **URL** te gebruiken (waarmee je direct ook informatie over het CRS kunt opvragen). Dit wordt o.a. gedaan in OGC APIs. 

Ik zou daarom schrijven "Name Type Specification (NTS), Uniform Resource names (URN), of Uniform Resource Locators (URL) gebruikt worden.

**Comment by JvGldr** [comment]
Tekst conform opmerking aangepast
