### ISSUE TITLE
Verwijzing naar iso19107

### ISSUE THREAD

**Issue by MichelGrothe** [Geonovum/raamwerk-geostandaarden#18]
In paragraaf 6.2 wordt de verwijzing opgenomen naar iso19107 en naar iso-19107-2003 (zie tabel). De iso-19107-2003 is inmiddels herzien: iso-19107-2019. Moeten deze opgelijnd worden?

**Comment by lvdbrink** [comment]
De oude versie uit 2003 is nog steeds in gebruik en wordt nog steeds aangehaald door erop gebaseerde standaarden. Overstappen op de nieuwe is niet zo eenvoudig, dus ik heb de verwijzing naar de 2003 versie bewust laten staan.

**Comment by PalmJanssen** [comment]
Goed besluit.
