### ISSUE TITLE
Informatieve referentielijst aan te passen?

### ISSUE THREAD

**Issue by MichelGrothe** [Geonovum/raamwerk-geostandaarden#19]
De verwijzing naar iso19115-2014 wordt (automatisch door respec?) opgenomen in de lijst met informatie referenties. Het is echter een normatieve referentie. Hoe dit te wijzigen?

**Comment by lvdbrink** [comment]
Nee, de verwijzing naar de 2014 versie van ISO19115 lijkt me juist niet normatief. We hanteren de oudere versie van 19115, zoals in het metadata hoofdstuk wordt uitgelegd. 

Respec heeft hier inderdaad automatisch een informatieve referentie van gemaakt, omdat de referentie in een Note staat en niet in de gewone tekst. 

Hier staat uitgelegd hoe Respec bepaalt of iets een normatieve of informatieve referentie moet zijn: https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide#normative-vs-informative-references
