### ISSUE TITLE
Update OGC API - Environmental Data Retrieval Standard

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/raamwerk-geostandaarden#29]
OGC API - Environmental Data Retrieval Standard (EDR) zit op v1.1, raamwerk verwijst nog naar 1.0.1. 

v1.1 URL: https://docs.ogc.org/is/19-086r6/19-086r6.html

**Comment by MichelGrothe** [comment]
Issue is hetzelfde als issue #23
