### ISSUE TITLE
review reactie op raamwerk geostandaarden 4.0

### ISSUE THREAD

**Issue by dkrijtenburg-GNM** [Geonovum/raamwerk-geostandaarden#3]
nav mail van Michel van 2-12 heb i keen paar opmerkingen over het document:

- actualisatie: wellicht goed om ook IBDS en het federatief datastelsel te noemen en onze standaarden daar in moeten passen. (de houtskoolschets plaat toevoegen waar in het midden de standaarden staan)
- https://geonovum.github.io/raamwerk-geostandaarden/#het-3-laags-pacelayer-model/ Tip: hier een link opnemen naar Gartner
- https://geonovum.github.io/raamwerk-geostandaarden/#kwaliteit-van-informatiemodellen : NEN 3610 conformiteit vervangen door NEN3610:2022 conformiteit? of is dat te specifiek. of wellicht - de laatste versie van NEN3610
- ook in https://geonovum.github.io/raamwerk-geostandaarden/#informatiemodellen-0 een paragraaf toevoegen over MIM-conformiteit. MIM staat nu alleen als architectuur principe genoemd. Ook hier noemen dat men moet aansluiten op de laatste versie van MIM.
- ik ben geen linked data expert, maar ik zou verwachten dat hier meer over gezegd zou worden dan alleen linked data API's, bv het opleveren van een ontologie

**Comment by JvGldr** [comment]
Bullet 2: Het Gartner model is intussen veranderd naar System of Records, System of Differentiation en System of Innovation. Een link opnemen werkt dan verwarrend. Vpor ons doel: het raamwerk past System of Records, System of Integration en System of Engagement beter. Ik zal daar een stukje tekst aan wijden.

**Comment by PalmJanssen** [comment]
- bullet 3: Is aangepast. Noem nu nen 3610:2022 conformiteit
- bullet 4: MIM als extra paragraaf toegevoegd: https://geonovum.github.io/raamwerk-geostandaarden/#mim-metamodel-voor-informatiemodellering

**Comment by MichelGrothe** [comment]
Bullit 1: Ik ben daar geen voorstander van; In IBDS en FDS zit vooralsnog relatief weinig geo (degeobasisregistraties en een enkele sectorregistratie; zie NORA pagina over sectorregistraties) en is nog niet veel meer dan inderdaad een 'houtskoolschets'.  

Bullit 5: Ontologie komt bij informatiemodellen en de paragraaf over semantische samenhang ter sprake.

**Comment by MichelGrothe** [comment]
Alle 5 bullits zijn besproken en verwerkt.
