### ISSUE TITLE
Datagebruik voor een doel niet verplicht

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/raamwerk-geostandaarden#4]
In [2.5.4 Data](https://geonovum.github.io/raamwerk-geostandaarden/#data) wordt dit gezegd:
> Data wordt voor een bepaald doel ingewonnen, en moet ook voor dat doel worden gebruikt.

Niet mee eens. Volgens mij hebben wij nooit eerder zo'n soort regel gesteld. En data kan best breder gebruikt worden dan waar het oorspronkelijk voor bedoeld was. 

In de basisregistraties heb je wel te maken met verplicht gebruik (eis 3 van de [12 eisen Stelsel van basisregistraties](https://www.digitaleoverheid.nl/overzicht-van-alle-onderwerpen/stelsel-van-basisregistraties/12-eisen-stelsel-van-basisregistraties/). Maar dat wordt hier neem ik aan niet bedoeld. Het Raamwerk geostandaarden is veel breder dan het stelsel van basisregistraties.

**Comment by JvGldr** [comment]
@lvdbrink ik bedoel hier doelbinding. Die regel hebben wij  niet gesteld, maar het is wel zo dat niet alle data overal voor gebruikt mag worden. Ik zal dat beter uitleggen in de tekst.

**Comment by lvdbrink** [comment]
Maar is dat iets waar Geonovum iets over moet zeggen. Dat hebben wij toch nooit gedaan? En bovendien, het raamwerk geostandaarden gaat over standaarden, daar past dit niet bij.

**Comment by JvGldr** [comment]
Dat klopt, dus ik zal de tekst aanpassen.

**Comment by JvGldr** [comment]
done
