### ISSUE TITLE
Term "data" enkelvoud vs meervoud

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/raamwerk-geostandaarden#5]
In het Raamwerk wordt niet consistent enkelvoud of meervoud gebruikt waar geschreven wordt over "data".

**Comment by JvGldr** [comment]
ik heb het architectuur hoofdstuk gescand en aangepast. ik heb het altijd over 'data' in meervoud.

**Comment by MichelGrothe** [comment]
Ik heb de overige hoofdstukken gecheckt en 'data' en 'metadata' in meervoud toegepast.
