### ISSUE TITLE
Verwijzingen naar O&M op elkaar afstemmen

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/raamwerk-geostandaarden#7]
In [hfd 3 Informatiemodellen](https://geonovum.github.io/raamwerk-geostandaarden/#overzicht-standaarden-informatiemodellen-voor-nederland) wordt verwezen naar Observations & Measurements deel 1 en 2, beide versie 1.0. 

In [hfd 6 Uitwisselformaten](https://geonovum.github.io/raamwerk-geostandaarden/#sensordata-uitwisselstandaarden) wordt verwezen naar Observations, Measurements & Samples deel 1 versie 2.0. 

Punten:
- De verwijzingen [OaM1] en [OaM2] werken niet (niet in config.js opgenomen?)
- Moeten we verwijzen naar O&M 1.0 of naar OMS 2.0 of naar beide. 
- In welk hoofdstuk horen de verwijzingen thuis?

**Comment by PalmJanssen** [comment]
Done.

In hfstk 3 is nu opgenomen:

"Observations and Measurements - XML Implementation v2.0", (https://portal.ogc.org/files/?artifact_id=41510)
en 
"OGC Timeseries Profile of Observations and Measurements v1.0", (http://docs.opengeospatial.org/is/15-043r3/15-043r3.html)

In hfstk 6 is deze toegevoegd: Observations and Measurements - XML Implementation 2.0
