### ISSUE TITLE
Verwijzing CityGML in hfd 3 updaten

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/raamwerk-geostandaarden#8]
De verwijzing naar CityGML in [hoofdstuk 3 Informatiemodellen[(https://geonovum.github.io/raamwerk-geostandaarden/#overzicht-standaarden-informatiemodellen-voor-nederland) verwijst naar:

OpenGIS City Geography Markup Language (CityGML) Encoding Standard, version 2.0 [[CityGML](https://geonovum.github.io/raamwerk-geostandaarden/#bib-citygml)]

Deze versie is verouderd. Updaten naar versie 3.0. Hier wordt al wel naar verwezen in [hoofdstuk 6.5 3D data uitwisselstandaarden](https://geonovum.github.io/raamwerk-geostandaarden/#x3d-data-uitwisselstandaarden). 

Deze verwijzing past het beste in hfd 3 omdat dit een informatiemodel is en geen uitwisselformaat (sinds v 3.0 van CityGML zijn deze uit elkaar getrokken). 

Punt is wel dat het XML-gebaseerde uitwisselformaat voor CityGML 3.0 nog niet gereed is. Dus in hfd 6 moeten we wellicht wél nog CityGML 2.0 noemen!

**Comment by PalmJanssen** [comment]
Done:

In hfstk 3 noem ik nu:
OGC City Geography Markup Language (CityGML) Part 1: Conceptual Model Standard v3.0. [[CityGML3]]

In hfstk 6: OGC City Geography Markup Language (CityGML) Encoding Standard, version 2.0 [[CityGML2]]
