### ISSUE TITLE
Verwarring knowledge graphs en begrippenkaders

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/raamwerk-geostandaarden#9]
In paragraaf [3.3 Semantische samenhang](https://geonovum.github.io/raamwerk-geostandaarden/#semantische-samenhang) staat dat 

> Knowledge graphs worden ontwikkeld om begrippenkaders aan elkaar te verbinden.

Hier worden SKOS en OWL door elkaar gehaald m.i. Ik zou ervan maken: "Knowledge graphs worden ontwikkeld om informatiemodellen aan elkaar te verbinden."

**Comment by MichelGrothe** [comment]
Ik heb het aangepast conform Linda's suggestie "Knowledge graphs worden ontwikkeld om informatiemodellen aan elkaar te verbinden".
